version: '3.9'

services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4000:4173"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:7000"
    volumes:
      - uploads:/data/uploads
volumes:
   uploads:
