get http://localhost:7000/users

####

get http://localhost:7000/users/62a649058ae77b41b9af6d82

####

post http://localhost:7000/users
Content-Type: application/json

{
    "firstName": "Manzi",
    "lastName" : "Cedric",
    "gender" : "male",
    "email" : "mcedro@gmail.com",
    "password" : "hastup"
}
####

put http://localhost:7000/users/62a65126fe933b08abfc017e
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyYTY1MTI2ZmU5MzNiMDhhYmZjMDE3ZSIsImZpcnN0TmFtZSI6Ik1hbnppIiwibGFzdE5hbWUiOiJDZWRyaWMiLCJnZW5kZXIiOiJtYWxlIiwiaWF0IjoxNjU1MDY3MzE4LCJleHAiOjE3NDE0NjczMTh9.OLEKgpbK8rNVHBk_C0sK4eIcBdxUhitlLzK2ukM5yV0

{
    "firstName": "Kalisa",
    "lastName" : "Cedric",
    "gender" : "male",
    "password" : "hastupo"
}

####

delete http://localhost:7000/users/62a649058ae77b41b9af6d82
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyYTY1MTI2ZmU5MzNiMDhhYmZjMDE3ZSIsImZpcnN0TmFtZSI6Ik1hbnppIiwibGFzdE5hbWUiOiJDZWRyaWMiLCJnZW5kZXIiOiJtYWxlIiwiaWF0IjoxNjU1MDY3MzE4LCJleHAiOjE3NDE0NjczMTh9.OLEKgpbK8rNVHBk_C0sK4eIcBdxUhitlLzK2ukM5yV0
####

post http://localhost:7000/users/login
Content-Type: application/json

{
    "email" : "mcedro@gmail.com",
    "password" : "hastup"
}
